# Generated by Django 5.1.6 on 2025-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
