# Generated by Django 5.1.6 on 2025-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0003_remove_project_category_project_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='carousels/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
