# Generated by Django 5.1.6 on 2025-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0004_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carousel',
            name='sort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carousel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
