# Generated by Django 5.1.6 on 2025-04-15 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0005_carousel_created_date_carousel_interval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='title', max_length=100, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='swiper/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='body',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_web_address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='title_project_detail', max_length=100, null=True, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('main_picture', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('project_web_address', models.URLField(blank=True, null=True)),
                ('project_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_project', to='myConstruction.customer')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myConstruction.projecttype')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags_project_detail', to='myConstruction.tag')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_project_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
