# Generated by Django 5.1.6 on 2025-04-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0006_swiper_remove_project_body_remove_project_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='swiper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myConstruction.swiper'),
        ),
    ]
