# Generated by Django 5.1.6 on 2025-04-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0007_projectdetail_swiper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='swiper',
        ),
        migrations.AddField(
            model_name='swiper',
            name='project_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myConstruction.projectdetail'),
        ),
    ]
