# Generated by Django 5.1.6 on 2025-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0008_remove_projectdetail_swiper_swiper_project_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='swiper/'),
        ),
        migrations.DeleteModel(
            name='Swiper',
        ),
    ]
