# Generated by Django 5.1.6 on 2025-04-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0009_projectdetail_image_path_delete_swiper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='image_path',
        ),
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='title', max_length=100, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='swiper/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('project_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myConstruction.projectdetail')),
            ],
        ),
    ]
