# Generated by Django 5.1.6 on 2025-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0010_remove_projectdetail_image_path_swiper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiper',
            name='project_detail',
        ),
    ]
