# Generated by Django 5.1.6 on 2025-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0011_remove_swiper_project_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='name_of_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
