# Generated by Django 5.1.6 on 2025-04-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0012_carousel_name_of_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='caption_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
