# Generated by Django 5.1.6 on 2025-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0013_carousel_caption_carousel_caption_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='data',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
