# Generated by Django 5.1.6 on 2025-04-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0014_news_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
