# Generated by Django 5.1.6 on 2025-04-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0015_alter_news_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiper',
            options={'ordering': ['sort']},
        ),
        migrations.AddField(
            model_name='swiper',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
