# Generated by Django 5.1.6 on 2025-05-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myConstruction', '0016_alter_swiper_options_swiper_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='Swiper',
        ),
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_project', to='myConstruction.customer'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_web_address',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectDetail',
        ),
    ]
