# Generated by Django 5.1.6 on 2025-05-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0017_remove_projectdetail_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='end_date_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='start_date_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
