# Generated by Django 5.1.6 on 2025-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0018_carousel_end_date_at_carousel_start_date_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
