# Generated by Django 5.1.6 on 2025-05-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0019_carousel_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='timestamp',
        ),
    ]
