# Generated by Django 5.1.3 on 2025-05-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0020_remove_carousel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
