# Generated by Django 5.1.3 on 2025-05-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0025_alter_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='name_author',
        ),
    ]
