# Generated by Django 5.1.3 on 2025-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0026_rename_name_author_name_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
