# Generated by Django 5.1.3 on 2025-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0027_alter_author_name_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='author',
            new_name='authors',
        ),
        migrations.AlterField(
            model_name='author',
            name='name_author',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
