# Generated by Django 5.1.3 on 2025-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0028_rename_author_news_authors_alter_author_name_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bodyAfterBlockquote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='bodyAfterImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='main_picture_b',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='title2',
            field=models.CharField(blank=True, default='title2_News', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title3',
            field=models.CharField(blank=True, default='title3_News', max_length=100, null=True, unique=True),
        ),
    ]
