# Generated by Django 5.1.3 on 2025-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0029_news_bodyafterblockquote_news_bodyafterimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title2',
            field=models.CharField(blank=True, default='title2_News', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title3',
            field=models.CharField(blank=True, default='title3_News', max_length=100, null=True),
        ),
    ]
