# Generated by Django 5.1.3 on 2025-05-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0030_alter_news_title2_alter_news_title3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title3',
        ),
        migrations.AddField(
            model_name='news',
            name='titleN',
            field=models.CharField(blank=True, default='titleN_News', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='titleText',
            field=models.CharField(blank=True, default='titleText_News', max_length=100, null=True),
        ),
    ]
