# Generated by Django 5.1.3 on 2025-05-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0031_remove_news_title2_remove_news_title3_news_titlen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='titleN',
        ),
        migrations.RemoveField(
            model_name='news',
            name='titleText',
        ),
    ]
