# Generated by Django 5.1.3 on 2025-05-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0032_remove_news_titlen_remove_news_titletext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='bodyAfterBlockquote',
        ),
        migrations.RemoveField(
            model_name='news',
            name='bodyAfterImage',
        ),
        migrations.RemoveField(
            model_name='news',
            name='main_picture_b',
        ),
    ]
