# Generated by Django 5.1.3 on 2025-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0033_remove_news_bodyafterblockquote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, default='title_News', max_length=100, null=True),
        ),
    ]
