# Generated by Django 5.1.3 on 2025-05-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0034_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='titleN',
            field=models.CharField(blank=True, default='titleN_News', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='titleText',
            field=models.CharField(blank=True, default='titleText_News', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, default='title_project', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
