# Generated by Django 5.1.3 on 2025-05-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0035_news_titlen_news_titletext_alter_author_name_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bodyAfterBlockquote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='bodyAfterImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='main_picture_b',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
    ]
