# Generated by Django 5.1.3 on 2025-05-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0037_remove_news_bodyafterblockquote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_title',
            field=models.CharField(blank=True, default='name_News', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='name_title_blockquote',
            field=models.CharField(blank=True, default='name_News_blockquote', max_length=100, null=True),
        ),
    ]
