# Generated by Django 5.1.3 on 2025-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0039_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
