# Generated by Django 5.1.3 on 2025-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0040_remove_news_image_news_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
