# Generated by Django 5.1.3 on 2025-05-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0042_remove_image_name_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
