# Generated by Django 5.1.3 on 2025-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0046_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name_customer',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
