# Generated by Django 5.1.3 on 2025-05-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0048_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
