# Generated by Django 5.1.3 on 2025-05-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0049_remove_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Author_project', to='myConstruction.author'),
        ),
    ]
