# Generated by Django 5.1.3 on 2025-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0052_news_dislike_count_news_disliked_by_news_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
