# Generated by Django 5.1.3 on 2025-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0054_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
