# Generated by Django 5.1.3 on 2025-08-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0055_comment_published_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsDetails',
        ),
        migrations.AddField(
            model_name='comment',
            name='email_comment',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='username_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='website_comment',
            field=models.URLField(blank=True, null=True),
        ),
    ]
