# Generated by Django 5.1.3 on 2025-08-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0056_delete_newsdetails_comment_email_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='body_author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
