# Generated by Django 5.1.3 on 2025-08-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0057_author_body_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
        migrations.AddField(
            model_name='news',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='Author_News', to='myConstruction.author'),
        ),
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='Author_project', to='myConstruction.author'),
        ),
    ]
