# Generated by Django 5.1.3 on 2025-08-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0058_remove_news_authors_remove_project_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
