# Generated by Django 5.1.3 on 2025-08-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0059_comment_author_reply_comment_author_reply_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_author',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
