# Generated by Django 5.1.3 on 2025-08-08 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0060_author_image_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myConstruction.author'),
        ),
        migrations.RemoveField(
            model_name='news',
            name='authors',
        ),
        migrations.AddField(
            model_name='news',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myConstruction.author'),
        ),
    ]
