# Generated by Django 5.1.3 on 2025-08-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0061_remove_project_authors_project_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(blank=True, to='myConstruction.author'),
        ),
        migrations.RemoveField(
            model_name='news',
            name='authors',
        ),
        migrations.AddField(
            model_name='news',
            name='authors',
            field=models.ManyToManyField(blank=True, to='myConstruction.author'),
        ),
    ]
