# Generated by Django 5.1.3 on 2025-08-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0062_remove_project_author_project_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_news', to='myConstruction.author'),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_author', to='myConstruction.author'),
        ),
    ]
