# Generated by Django 5.1.3 on 2025-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0063_remove_news_authors_remove_project_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='title_swiper', max_length=100, null=True)),
                ('name_swiper', models.CharField(blank=True, default='name_swiper', max_length=100, null=True)),
                ('main_image', models.FileField(blank=True, null=True, upload_to='swiper/')),
                ('name_of_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('job_swiper', models.CharField(blank=True, default='job_swiper', max_length=100, null=True)),
                ('description_swiper', models.CharField(blank=True, default='description_swiper', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
