# Generated by Django 5.1.3 on 2025-08-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0064_swiper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiper',
            name='description_swiper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swiper',
            name='job_swiper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swiper',
            name='name_swiper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
