# Generated by Django 5.1.3 on 2025-08-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0066_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
