# Generated by Django 5.1.3 on 2025-08-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0067_content_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content5',
        ),
    ]
