# Generated by Django 5.1.3 on 2025-08-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0068_remove_content_content5'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, default='name_content', max_length=100, null=True),
        ),
    ]
