# Generated by Django 5.1.3 on 2025-08-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0069_content_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='project',
            name='name_alt',
            field=models.CharField(blank=True, default='name_alt', max_length=100, null=True),
        ),
    ]
