# Generated by Django 5.1.3 on 2025-08-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0070_delete_content_project_name_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
