# Generated by Django 5.1.3 on 2025-08-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0072_delete_servicedetail_service_body_service_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delay_time',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='iconname1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='iconname2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='iconname3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
