# Generated by Django 5.1.3 on 2025-08-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0073_service_delay_time_service_iconname1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='title_icon',
            new_name='title_sabet',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
