# Generated by Django 5.1.3 on 2025-08-09 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0074_rename_title_icon_service_title_sabet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='body',
        ),
        migrations.RemoveField(
            model_name='service',
            name='content',
        ),
        migrations.RemoveField(
            model_name='service',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='delay_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='iconname1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='iconname2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='iconname3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='main_picture',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_alt',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_sabet',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myConstruction.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myConstruction.service')),
            ],
        ),
    ]
