# Generated by Django 5.1.3 on 2025-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0076_servicesfeature_main_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, default='title_service', max_length=100, null=True),
        ),
    ]
