# Generated by Django 5.1.3 on 2025-08-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0077_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='title_service', max_length=100),
        ),
    ]
