# Generated by Django 5.1.3 on 2025-08-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0078_alter_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
