# Generated by Django 5.1.3 on 2025-08-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0079_feature_body_feature_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesfeature',
            name='main_picture',
        ),
        migrations.RemoveField(
            model_name='servicesfeature',
            name='name_alt',
        ),
    ]
