# Generated by Django 5.1.3 on 2025-08-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0080_remove_servicesfeature_main_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesfeature',
            name='main_picture',
            field=models.FileField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='servicesfeature',
            name='name_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
