# Generated by Django 5.1.3 on 2025-08-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0081_servicesfeature_main_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesfeature',
            name='main_picture',
        ),
        migrations.RemoveField(
            model_name='servicesfeature',
            name='name_alt',
        ),
    ]
