# Generated by Django 5.1.3 on 2025-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConstruction', '0083_servicesdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesdetail',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesdetail',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
